import {employees,employee,euros,status,totals} from '@/lib/rules.mjs';
import {load, type Transaction} from '@/lib/server';
import {ActionForm,Field,Split,Allocation,Mapping} from './forms';
export const dynamic='force-dynamic';
const cash=(cents:number)=>euros(cents/100);
export default async function Page({searchParams}:{searchParams:Promise<{role?:string}>}){
 const params=await searchParams,actor=employees.some(e=>e.id===params.role)?params.role!:'richard',person=employee(actor),manager=person.role==='manager';
 let data:{records:Transaction[];notices:any[];mappings:any[];chats:any[]}={records:[],notices:[],mappings:[],chats:[]},error='';
 try{data=await load(actor);}catch(e){error=e instanceof Error?e.message:'Connection unavailable';}
 const results=totals(data.records),pending=data.records.filter(t=>!t.decision);
 return <main>
 <header><a className="brand" href="/">fi<span>Friends Included</span></a><span className="author">Elīze Ļaksa · Day 4</span></header>
 <div className="hero"><div><p className="eyebrow">GOOD COMPANY. CLEAR NUMBERS.</p><h1>Every guest has a story.<br/><em>Every euro, a place.</em></h1><p className="intro">The finance desk for convincing relatives and unforgettable university friends.</p></div><div className="stamp">FRIENDS<br/><strong>included.</strong><small>All friendships expire at checkout.</small></div></div>
 <section className="toolbar"><div><p className="eyebrow">YOUR WORKSPACE</p><h2>{person.name}</h2><p>{manager?'Review decisions, connect Telegram and follow the numbers.':person.role==='sales'?'Record a paid sale and propose its commission split.':'Record a paid expense and propose where it belongs.'}</p></div><form><label htmlFor="role">Demonstration role</label><div className="role"><select id="role" name="role" defaultValue={actor}>{employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><button>Switch role →</button></div></form></section>
 <nav className="quick-nav"><a href="#entry">{manager?'Review queue':'New transaction'}</a><a href="#records">Records & retries</a>{manager&&<><a href="#dashboard">Financial dashboard</a><a href="#setup">Telegram setup</a></>}</nav>
 {error?<aside role="alert"><strong>Connection setup required</strong><p>{error}</p><p>Follow START-HERE-LV.md in the project archive. Records are never simulated.</p></aside>:<>
 {manager&&<section id="dashboard"><div className="section-title"><div><p className="eyebrow">THE BIG PICTURE</p><h2>Company at a glance</h2></div><span>All amounts EUR · No VAT</span></div><div className="dashboard">
 {(['A','B'] as const).map(k=><article className="metric" key={k}><p className="eyebrow">PROJECT {k}</p><h3>{k==='A'?'Respectable Relatives':'Drunk University Friends'}</h3><strong className="total">{cash(results.projects[k].result)}</strong><dl><dt>Approved income</dt><dd>{cash(results.projects[k].income)}</dd><dt>Commission expense</dt><dd>{cash(results.projects[k].commission)}</dd><dt>Allocated expenses</dt><dd>{cash(results.projects[k].expenses)}</dd></dl></article>)}
 <article className="metric dark"><p className="eyebrow">COMPANY RESULT</p><strong className="total">{cash(results.result)}</strong><dl><dt>Approved income</dt><dd>{cash(results.income)}</dd><dt>Sales commissions</dt><dd>{cash(results.commission)}</dd><dt>All recorded expenses</dt><dd>{cash(results.allExpenses)}</dd><dt>Company overhead</dt><dd>{cash(results.overhead)}</dd><dt>Awaiting allocation</dt><dd>{cash(results.awaiting)}</dd></dl></article></div>
 <p className="reconciliation">Reconciliation: {cash(results.projects.A.result)} + {cash(results.projects.B.result)} − {cash(results.overhead)} overhead − {cash(results.awaiting)} awaiting allocation = <strong>{cash(results.result)}</strong></p>
 <div className="commission-grid">{['Richard','Anastasia','Jean-Claude'].map((n,i)=><div key={n}><span>{n} · commission earned</span><strong>{cash(results.earned[i])}</strong></div>)}</div><p className="muted">Pending means internal approval: all reported services and expenses have already been paid. Pending sales earn no commission.</p></section>}
 <section id="entry" className="entry-section"><div><p className="eyebrow">{manager?'SVETLANA’S DESK':'ADD TO THE LEDGER'}</p><h2>{manager?'Decisions, with context.':person.role==='sales'?'A sale worth celebrating.':'Every expense accounted for.'}</h2><p>{manager?'Review original proposals below. Change a split or allocation before approving. You may leave any item pending.':'Use this form or the Telegram bot. Both follow the same validation and calculation rules.'}</p></div>
 {!manager?<div className="form-card"><ActionForm actor={actor} action={person.role==='sales'?'sale':'expense'} label={person.role==='sales'?'Record sale →':'Record expense →'}><Field name="reference" label="Unique reference"/><Field name="description" label="Description"/><Field name="amount" label="Amount (€)" type="number"/>{person.role==='sales'?<><Field name="customer" label="Customer"/><label>Project<select name="project"><option value="A">A · Respectable Relatives</option><option value="B">B · Drunk University Friends</option></select></label><p>Proposed commission split · must total 100%</p><Split/></>:<><label>Category<select name="category"><option>Materials</option><option>Travel</option><option>Other</option></select></label><Allocation/></>}</ActionForm></div>:<div className="queue">{pending.length===0?<div className="empty"><h3>All caught up.</h3><p>No transactions awaiting decisions.</p></div>:pending.map(t=><article className="decision-card" key={t.reference}><div className="section-title"><h3>{t.reference} · {cash(Math.round(t.proposal.amount*100))}</h3><span className="badge">{status(t)}</span></div><p>{t.proposal.description}</p><p className="muted">{employee(t.actor).name} · {t.kind==='sale'?`${t.proposal.customer} · Project ${t.proposal.project}`:t.proposal.category}</p><p><strong>Original proposal:</strong> {t.kind==='sale'?t.proposal.split.join(' / ')+'%':t.proposal.allocation}</p><ActionForm actor={actor} action="approve" reference={t.reference} label="Approve decision">{t.kind==='sale'?<Split values={t.proposal.split}/>:<Allocation value={t.proposal.allocation}/>}</ActionForm></article>)}</div>}
 </section>
 <section id="records" className="records"><div className="section-title"><div><p className="eyebrow">THE LEDGER</p><h2>{manager?'All transactions':'Your transactions'}</h2></div><span>{data.records.length} records</span></div>
 {!data.records.length?<div className="empty"><h3>A fresh page.</h3><p>Saved transactions will appear here and persist after refreshing.</p></div>:<div className="table-wrap"><table><thead><tr><th>Transaction</th><th>Amount / status</th><th>Original → final</th><th>Integrations</th></tr></thead><tbody>{data.records.map(t=><tr key={t.reference}><td><strong>{t.reference} · {t.kind}</strong><small>{t.proposal.description}</small><small>{employee(t.actor).name}</small><small>{new Date(t.created_at).toISOString()} · {t.source}</small>{t.kind==='sale'&&<small>{t.proposal.customer} · Project {t.proposal.project}</small>}</td><td><strong>{euros(t.proposal.amount)}</strong><span className="badge">{status(t)}</span></td><td>{t.kind==='sale'?<><small>Proposed: {t.proposal.split.join(' / ')}%</small><small>Approved: {t.decision?t.decision.split.join(' / ')+'%':'—'}</small><small>Earned R / A / J: {(t.decision?.earned??[0,0,0]).map(cash).join(' / ')}</small></>:<><small>Proposed: {t.proposal.allocation}</small><small>Final: {t.decision?.allocation??'—'}</small></>}</td><td><small>Sheets: <strong>{t.sync_status}</strong></small>{data.notices.filter(n=>n.reference===t.reference).map(n=><small key={n.id}>Telegram ({n.event}): {n.status}{n.error&&<span title={n.error}> · delivery needs attention</span>}</small>)}{(t.sync_status!=='Synced'||data.notices.some(n=>n.reference===t.reference&&n.status!=='Sent'))&&<ActionForm actor={actor} action="retry" reference={t.reference} label="Retry sync / delivery">{null}</ActionForm>}</td></tr>)}</tbody></table></div>}</section>
 {manager&&<section id="setup" className="entry-section"><div><p className="eyebrow">MANAGER SETUP</p><h2>The right person.<br/>The right message.</h2><p>First open the bot and send /start. Enter its numeric user ID below. Linking the same account to another employee replaces its previous mapping.</p><p>Bot submissions always keep their original chat destination. Website decisions use the employee’s currently linked account.</p></div><div className="form-card"><Mapping actor={actor}/><h3>Current links</h3>{data.mappings.length?data.mappings.map(m=><p key={m.employee_id}>{employee(m.employee_id).name}: {m.user_id}</p>):<p>No accounts linked yet.</p>}<details><summary>Accounts that started the bot</summary>{data.chats.map(c=><p key={c.user_id}>{c.user_id}</p>)}</details></div></section>}
 </>}
 <aside><strong>How to use this desk</strong><p>Choose a Demonstration role and switch. Richard, Anastasia and Jean-Claude submit sales; Kevin submits expenses. Svetlana reviews decisions, changes proposals before approval and manages Telegram links. Use Retry beside a record if an integration fails. This is an instructor demonstration with an open role selector, not an authenticated production finance service.</p></aside>
 <footer><p>Friends Included Ltd · Elīze Ļaksa</p><nav><a href="https://t.me/weddingtask_bbot">Telegram bot ↗</a><a href="https://docs.google.com/spreadsheets/d/1xEAkjsaR-hMR-qZTiCHCGokJ5Fxw6iJkmfBMhTKTrDs/edit">Google Sheets ↗</a><a href="https://github.com/elizelaksa/friends-included-finance">GitHub ↗</a></nav></footer></main>;
}
